#fail_fast: true
repos:
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: false
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
    -   id: docformatter
-   repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    -   id: isort # Sort imports
        name: isort (python)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast # Valid Python
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ["--fix=lf"]
    -   id: name-tests-test
        args: ["--django"]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=.vscode/pylint.rc"]
